Update README.md
combatopera/lagoon pull request #7
Opened 2020-10-09 05:01 UTC by aoxolotl

Addresses Issue #6

2020-10-09 16:46 UTC, combatopera requested changes
thanks for the pr, please see inline comment

2020-10-09 16:46 UTC, combatopera commented on README.md
> +```
this is misleading - only the screen.py module requires gnu screen, it's not needed to be able to use the rest of lagoon. would it make more sense to have this message in the Concern readme, as that does not work without gnu screen? ideally users shouldn't have to dig into the readmes of libraries (lagoon) to be able to use the application (Concern)

2020-10-24 12:14 UTC, combatopera commented
hi @aoxolotl, are you still working on this?

2020-10-29 10:34 UTC, aoxolotl commented
Hey! I will wrap it up this weekend

2020-11-04 06:08 UTC, aoxolotl commented on README.md
> +```
Cool. So I'll shift this to Concern readme and say "screen.py module requires gnu screen which can be installed using..."

2020-12-27 14:54 UTC, closed without merging